version: '2'
services:
  app:
    container_name: app
    build: .
    ports:
      - "4567:4567"
    volumes:
     - .:/opt/app
     - bundle:/usr/local/bundle
    links:
      - selenium
      - mongo
    command: bash -c "cd /opt/app && bundle install --jobs 3 && bundle exec rake"

  selenium:
    container_name: chrome
    image: selenium/standalone-chrome
    ports:
        - "4444:4444"
    logging:
      driver: none

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
        - "27017:27017"

volumes:
  bundle:
    driver: local
